name: Build

on: push

jobs:
  build_wheels_36:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.4.0

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp36-*
          CIBW_BEFORE_BUILD: python -m pip install --force-reinstall --no-cache-dir numpy==1.13.0
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
          
  build_wheels_37:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.4.0

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp37-*
          CIBW_BEFORE_BUILD: python -m pip install --force-reinstall --no-cache-dir numpy==1.14.5
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
          
  build_wheels_38:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.4.0

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp38-*
          CIBW_BEFORE_BUILD: python -m pip install --force-reinstall --no-cache-dir numpy==1.17.3
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
          
  build_wheels_39:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.4.0

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp39-*
          CIBW_BEFORE_BUILD: python -m pip install --force-reinstall --no-cache-dir numpy==1.19.3
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
          
  build_wheels_310:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.4.0

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp310-*
          CIBW_BEFORE_BUILD: python -m pip install --force-reinstall --no-cache-dir numpy==1.21.3
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
