name: Build

on: push

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: ['3.9']
        include:
          - python-version: '3.9'
            numpy-version: 1.19.3
            ci-build-regex: cp39-*
            
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.5.0

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_ARCHS: ARM64
          CIBW_BUILD: ${{ matrix.ci-build-regex }}
          CIBW_BEFORE_BUILD: python -m pip install --force-reinstall --no-cache-dir numpy==${{ matrix.numpy-version }}

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
