name: Build

on: push

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy >= 1.13
          python -m pip install numpy --upgrade
          python -m pip install cibuildwheel==2.4.0

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
